print("--------------------------------")
print("- (1) Start New Arcade Game    -")
print("- (2) Start New Free Play Game -")
print("- (3) Load New Saved Game      -")
print("- (4) Display High Scores      -")
print("- (0) Exit Game                -")
print("--------------------------------")